-- Fresh development schema. Contains no exported user records or credentials.
CREATE TABLE IF NOT EXISTS dotdeck_user (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('user', 'moderator', 'admin') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  banned_at DATETIME NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_deck (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  description TEXT NULL,
  thumbnail_url TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  FOREIGN KEY (user_id) REFERENCES dotdeck_user(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_code_snippet (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deck_id BIGINT UNSIGNED NOT NULL,
  language VARCHAR(64) NULL,
  caption TEXT NULL,
  code MEDIUMTEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (deck_id) REFERENCES dotdeck_deck(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_tag_type (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_tag (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(80) NOT NULL UNIQUE,
  tag_type INT UNSIGNED NULL,
  is_official BOOLEAN NOT NULL DEFAULT FALSE,
  FOREIGN KEY (tag_type) REFERENCES dotdeck_tag_type(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_deck_tag (
  deck_id BIGINT UNSIGNED NOT NULL,
  tag_id BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (deck_id, tag_id),
  FOREIGN KEY (deck_id) REFERENCES dotdeck_deck(id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES dotdeck_tag(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_comment (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  deck_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  body TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  FOREIGN KEY (deck_id) REFERENCES dotdeck_deck(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES dotdeck_user(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_rating (
  user_id BIGINT UNSIGNED NOT NULL,
  deck_id BIGINT UNSIGNED NOT NULL,
  score TINYINT NOT NULL,
  PRIMARY KEY (user_id, deck_id),
  CHECK (score IN (-1, 1)),
  FOREIGN KEY (deck_id) REFERENCES dotdeck_deck(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES dotdeck_user(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_user_ban (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  actor_id BIGINT UNSIGNED NULL,
  reason TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES dotdeck_user(id) ON DELETE CASCADE,
  FOREIGN KEY (actor_id) REFERENCES dotdeck_user(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dotdeck_audit (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  actor_id BIGINT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  target_table VARCHAR(80) NOT NULL,
  target_id BIGINT UNSIGNED NULL,
  meta JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_id) REFERENCES dotdeck_user(id) ON DELETE SET NULL
) ENGINE=InnoDB;
